import { GetStaticProps } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import TodoList from '../src/entities/Todolist';
import useTodoListHook from '../src/presenters/useTodoListHook';
import styles from '../styles/Home.module.css';
type Item = {
  id: string;
  description: string;
  done: boolean;
};

export default function Home({ data }) {
  const [todos, todosDispatch] = useTodoListHook(data);
  const [todo, setTodo] = useState<string>('');
  const handleChange = (e: React.FormEvent<HTMLInputElement>) => {
    setTodo(e.currentTarget.value);
  };
  const handleEnter = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key == 'Enter') {
      const description = e.currentTarget.value;
      if (!description) return;
      todosDispatch('create', { description });
      setTodo('');
    }
  };

  const handleToggle = (e: React.MouseEvent<HTMLSpanElement, MouseEvent>) => {
    const id = e.currentTarget.dataset.key!;
    todosDispatch('toggle', { id });
  };

  const handleDelete = (e: React.FormEvent<HTMLSpanElement>) => {
    const id = e.currentTarget.dataset.key;
    todosDispatch('remove', { id });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}> TodoList </h1>
      <main className={styles.main}>
        <div>
          <input
            type="text"
            name="todo"
            id="todo"
            value={todo}
            onChange={handleChange}
            onKeyUp={handleEnter}
          />
        </div>
        <div>
          <hr />
        </div>
        <div className="todo-list-view">
          {todos.map((item) => (
            <div key={item.id} className={item.done ? styles.itemdone : ''}>
              <div>
                <span data-key={item.id} onClick={handleToggle}>
                  {item.description}
                </span>{' '}
                -{' '}
                <span
                  onClick={handleDelete}
                  data-key={item.id}
                  style={{ display: 'inline-block' }}
                >
                  X
                </span>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
export const getStaticProps: GetStaticProps = async (context) => {
  const response = await fetch('http://localhost:4000/todos');
  const todos = await response.json();
  return {
    props: {
      data: todos,
    },
  };
};
